//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRF_Beadando
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eredmeny
    {
        public int Id { get; set; }
        public string Nev { get; set; }
        public int Pont { get; set; }
        public int IdoIntervallum { get; set; }
        public int TablaMeret { get; set; }
    }
}
